### PR TITLE
Add SNIKE

### PR DESCRIPTION
**Pull request by snike-ada**
Image IFPS: QmVrumNnFm6zWy3oZ34LsaArygf6A1MaNQFHKAw9v4TPk2

Payment: [fc89d9f751708e5641d32f396609fa054f9b111d8f906701d24e4ed2a4415202](https://cardanoscan.io/transaction/fc89d9f751708e5641d32f396609fa054f9b111d8f906701d24e4ed2a4415202)

snike-small

### CODE REVIEW

**Comment by snike-ada** [comment]
@nmelentjevs @rexdavinci can you help with this one please

**Comment by glneto** [comment]
why was this closed? if you can't verify the token shouldn't the 100 ADA be refunded at least? @nmelentjevs

**Comment by nmelentjevs** [comment]
hey closed = verified too, it's live

**Comment by glneto** [comment]
doesn't look like it's verified 

https://app.dexhunter.io/swap?tokenIdSell=&tokenIdBuy=f0e3bb60e1e637e87cd3b49d7e3f2522fe84fec8600edfd8906cdf74534e494b45

is there anything else that needs to be done? @nmelentjevs

**Comment by glneto** [comment]
@nmelentjevs any news on this? the 6 decimals are not even being considered on DexHunter so I'm not sure the verification went through 🤔

this was already approved on cardano-token-registry, don't you guys look at this info? https://github.com/cardano-foundation/cardano-token-registry/pull/4998

**Comment by nmelentjevs** [comment]
sorry for delay, should be good now

**Pull request closed without merging**
